version: '3.1'
services:
  stats-service:
    build: ./statistic/stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zig123big
      - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: stat-dataBase
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zig123big

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-service
      - ewm-db
    environment:
      - STATS-SERVICE_URL=http://stats-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zig123big
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-dataBase
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zig123big