CREATE TABLE IF NOT EXISTS stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(100),
    uri VARCHAR(100),
    ip VARCHAR(15),
    add_time timestamp,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );